Repository OpenZeppelin/compact-contracts, pull requests merged in 2025-07, with the labels that each got.

#184 Fix symbol comment
  contracts/archive/src/ShieldedToken.compact
Labels: documentation

#186 Add NonFungibleToken Docs
  contracts/nonFungibleToken/src/NonFungibleToken.compact
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/api/nonFungibleToken.adoc
  docs/modules/ROOT/pages/nonFungibleToken.adoc
Labels: documentation, needs-review

#182 Unshielded Access Control
  contracts/accessControl/package.json
  contracts/accessControl/src/AccessControl.compact
  contracts/accessControl/src/test/AccessControl.test.ts
  contracts/accessControl/src/test/mocks/MockAccessControl.compact
  contracts/accessControl/src/test/simulators/AccessControlSimulator.ts
  contracts/accessControl/src/test/types/test.ts
  contracts/accessControl/src/test/utils/address.ts
  contracts/accessControl/src/witnesses/AccessControlWitnesses.ts
  contracts/accessControl/tsconfig.build.json
  contracts/accessControl/tsconfig.json
  contracts/accessControl/vitest.config.ts
  docs/antora.yml
  docs/modules/ROOT/nav.adoc
  docs/modules/ROOT/pages/accessControl.adoc
  docs/modules/ROOT/pages/api/accessControl.adoc
  yarn.lock
Labels: enhancement, under-review

#193 Fix circuit info in nft docs
  contracts/nonFungibleToken/src/NonFungibleToken.compact
Labels: documentation
